### ISSUE TITLE
Monday 2nd November - Task List

### ISSUE THREAD

**Issue by IwanJones41299** [IwanJones41299/Shopping-Hut#19]
#Programming Tasks
- [x] Create an add product feature
- [x] Create an edit product feature
- [x] Create an view product feature
- [x] Create an delete product feature

#Written Tasks
- [x] Look into getting some papers together for the lit review
- [x] Start the lit review - Section : background info on pwa's
